### ISSUE TITLE
Size limited to 40 bytes

### ISSUE THREAD

**Issue by xloem** [blockai/raw-op-return#2]
Should be increased.  Would be great to have an option:
- 0.9 compatible, 40 bytes
- 0.11 compatible, 80 bytes ?
- 0.12 compatible, 10k ?
- nonstandard, unlimited ?

https://bitcointalk.org/index.php?topic=418437.0 states that over 76 bytes needs an extra opcode.

**Comment by williamcotton** [comment]
Check out https://github.com/blockai/blockcast - it's a gzip compressed protocol that allows for much more than 40 bytes!

**Comment by xloem** [comment]
It looks nice but the docs state it is for development, and production deployment should use optimized OP_RETURN protocols.  Is this library a good candidate for such use?

**Comment by williamcotton** [comment]
The reason the docs say Blockcast is for development is so people are inclined to come up with a solution that fits in to to just a single transaction in order to conserve a scarce public resource in the Bitcoin blockchain.

Since Bitcoin itself is still at version 0.11.2, I'd say it is pretty safe to consider everything built on top of the current Bitcoin blockchain to be in development.

However, as an alternative, I just added support for 80 bytes of data in this raw-op-return module, so feel free to use either!
